version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: medium_app_dev
      MYSQL_USER: medium_dev
      MYSQL_PASSWORD: 6fc0e76c-d99e-4d25-9ce4-f287c982a8ca
    ports:
      - "3306:3306"
  api:
    build: .
    env_file:
      - .env
    environment:
      TYPEORM_HOST: db
    ports:
      - "3307:3000"
    command: npm run start:prod
  app:
    build: ../medium-app/
    env_file:
      - .env
    environment:
      TYPEORM_HOST: db
    ports:
      - "3308:80"